config/routes.rb
Rails.application.routes.draw do
  mount Bootsy::Engine => '/bootsy', as: 'bootsy'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  namespace :admin do
    resources :blog_posts, only: [:index, :show, :new, :create, :destroy, :edit, :update]
  end

  resources :blog_posts, only: [:index, :show]

  get "/agradecimento", to: "greetings#index"
  get "/agradecimento/download", to: "greetings#download"

  root to: 'blog_posts#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog_post.rb
class BlogPost < ApplicationRecord
  extend FriendlyId
  include Bootsy::Container


  has_one_attached :image
  validates :image, presence: true
  validates :content, presence: true
  validates :title, presence: true

  friendly_id :title, use: :slugged
end

app/controllers/admin/blog_posts_controller.rb
module Admin
  class BlogPostsController < ApplicationController
    before_action :find_blog_post, only: [:edit, :update]
    def index
      @blog_posts = BlogPost.all
    end

    def new
      @blog_post = BlogPost.new
    end

    def create
      @blog_post = BlogPost.new(blog_post_params)

      respond_to do |format|
        if @blog_post.save
          format.html { redirect_to admin_blog_posts_path(@blog_post), notice: 'Post criado com sucesso!' }
          format.json { render json: @blog_post }
        else
          format.html { render :new }
          format.json { render json: @blog_post.errors.full_messages }
        end
      end
    end

    def edit; end

    def update
      respond_to do |format|
        if @blog_post.update!(blog_post_params)
          format.html { redirect_to admin_blog_posts_path(@blog_post), notice: 'Post alterado com sucesso!' }
          format.json { render json: @blog_post }
        else
          format.html { render :edit }
          format.json { render json: @blog_post.errors.full_messages }
        end
      end
    end

    def destroy
      @blog_post = BlogPost.find(params[:id])

      @blog_post.destroy!

      respond_to do |format|
        format.html { redirect_to admin_blog_posts_path(), notice: "Post removed successfully!" }
        format.json { render json: {} }
      end
    end

    private

    def blog_post_params
      params.require(:blog_post).permit(:title, :content, :image, :bootsy_image_gallery_id)
    end

    def find_blog_post
      @blog_post = BlogPost.friendly.find(params[:id])
    end
  end
end

# @post.image.attach(params[:image])

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/blog_posts_controller.rb
class BlogPostsController < ApplicationController
  def index
    @blog_posts = BlogPost.all
  end

  def show
    @blog_posts = BlogPost.all
    @blog_post = BlogPost.friendly.find(params[:id])
  end
end

app/controllers/greetings_controller.rb
class GreetingsController < ApplicationController
  def index
    @ebook = params[:ebook]
  end

  def download
    send_file(File.join(Rails.root, 'public/ebooks', "#{ebook_kind}.pdf"))
  end

  private

  def ebook_kind
    case params[:ebook]
    when "endomarketing"
      "CLAQUETEBUSINESS_e-book_endomarketing"
    when "eventos"
      "CLAQUETEBUSINESS_e-book_eventos"
    when "lead"
      "CLAQUETEBUSINESS_e-book_geracao-leads"
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/blog_posts/edit.html.erb
<%= render partial: "admin/blog_posts/shared/form", locals: { action: "Editar Post" } %>

app/views/admin/blog_posts/index.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-lg-12">
      <div class="panel-body">
        <br>
        <%= link_to "Adicionar", new_admin_blog_post_path, class: "btn btn-success text-center btn-new" %>
        <br>
        <br>
        <br>
        <div class="table-responsive class=" col-md-12">
          <table class="table table-striped table-hovers">
            <thead>
              <tr>
                <th>Título</th>
                <th>Conteúdo</th>
                <th>Imagem</th>
                <th class="col-md-3 text-center">Opções</th>
              </tr>
            </thead>
            <tbody>
              <% @blog_posts.each do |blog_post| %>
              <tr>
                <td class="title-table" width="30%">
                  <%= blog_post.title %>
                </td>
                <td class="content-table" width="50%">
                  <%= blog_post.content %>
                </td>
                <td>
                  <%= image_tag blog_post.image.variant(resize: "200x200") %>
                </td>
                <td class="text-center">
                  <%= link_to edit_admin_blog_post_path(blog_post.id), class: "btn btn-primary btn-circle" do %>
                  <i class="fa fa-edit"></i>
                  <% end %>

                  <%= link_to admin_blog_post_path(blog_post.id), method: :delete,
                    class: "btn btn-danger btn-circle",
                    data: { confirm: "Deseja realmente deletar o Post com ID: #{blog_post.id}?", item: blog_post.title } do %>
                  <i class="fa fa-times"></i>
                </td>
              </tr>
              <% end %>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admin/blog_posts/new.html.erb
<%= render partial: "admin/blog_posts/shared/form", locals: { action: "Novo Post" } %>

app/views/admin/blog_posts/shared/_form.html.erb
<div class="panel panel-default">
  <div class="panel-body">
  <h1 class="page-header title_blog_post"><%= action %></h1>
    <div class="col-md-6 ">
      <%= form_for ([:admin, @blog_post]) do |f| %>
      <% if @blog_post.errors.any? %>
        <div class="alert alert-danger alert-dismissable">
          <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
          <% @admin.errors.full_messages.each do |message| %>
          <ul>
            <li><%= message %></li>
          </ul>
          <% end %>
        </div>
        <% end %>

        <div class="form-group">
          <div class="col-md-12">
            <%= f.label "Título" %>
            <%= f.text_field :title, autofocus: true, class:"form-control", placeholder:"título do post" %>
          </div>
        </div>

        <div class="form-group">
          <div class="col-md-12">
            <%= f.label "Imagem" %>
            <%= f.file_field :image, class:"form-control" %>
          </div>
        </div>
        <div class="form-group content">
          <div class="col-md-12">
            <%= f.label "Conteúdo" %>
            <%= f.bootsy_area :content, cols: 20, rows: 10, class:"form-control" %>
          </div>
        </div>
        <div class='btn-post row'>
          <div class="form-group col-md-4">
            <%= f.submit "Salvar", class:"btn btn-primary btn-block" %>
          </div>
          <div class="btn-back col-md-4">
            <%= link_to "Página principal", admin_blog_posts_path, class:"btn btn-secondary btn-block" %>
          </div>
        </div>

      <% end %>
    </div>
  </div>
</div>

app/views/blog_posts/index.html.erb
<div class="wrap-posts">
  <div class="posts row">
    <% @blog_posts.sample(3).each do |blog_post| %>
    <div class="post-image">
      <%= image_tag blog_post.image, class: "blog-post-image" %>
      <p class="blog-post-title">
        <%= blog_post.title %>
      </p>
      <div class="link-to-show">
        <%= link_to "Acessar", blog_post_path(blog_post.id), class: "btn btn-warning" %>
      </div>
    </div>
    <%end%>
  </div>
</div>

<%= render partial: "blog_posts/shared/leads_form" %>

app/views/blog_posts/shared/_leads_form.html.erb
<div class="leads form-body">
  <a name="form-body"></a>
  <p class="form-title">Quer aprender como o vídeo pode transformar seu negócio? Baixe seu e-book grátis agora
    mesmo!</p>

  <form id="contactForm">
    <input id="ip" type="hidden" value="">

    <div class="form-group">
      <input type="text" class="form-fields" id="name" placeholder="Nome Completo" required="required" name="nome" />
    </div>

    <div class="form-group">
      <input type="email" class="form-fields" id="email" placeholder="Digite seu email" required="required" name="email" />
    </div>

    <div class="form-group">
      <select class="form-fields" id="ebooks">
        <option value="" disabled selected>selecione seu e-Book</option>
        <option value="endomarketing" class="form-fields">Endomarketing e Engajamento de Colaboradores</option>
        <option value="eventos" class="form-fields">Engajamento online para eventos</option>
        <option value="lead" class="form-fields">Técnicas de geração de leads com vídeos</option>
      </select>
    </div>

    <div class="form-group">
      <button type="submit" class="btn btn-warning btn-form btn-lg">Enviar</button>
    </div>

  </form>
</div>

app/views/blog_posts/shared/_nav.html.erb
<nav>
  <div class="nav">
    <%= image_tag "claquete_logo.jpg", class: "logo", alt: "logo"  %>
    <%= link_to  "Claquete Business", blog_posts_path, class: "site-name"%>
    <div class="donwload-header">
      <a href="#form-body">Baixe seu e-Book</a>
    </div>
</nav>

app/views/blog_posts/show.html.erb
<div class="show-container">
  <div class="image-show">
    <%= image_tag @blog_post.image.variant(resize: "750x400"), class: "show-img" %>
  </div>
  <div class="title-show">
    <%= @blog_post.title %>
  </div>

  <div class="content-show">
    <%= @blog_post.content.html_safe %>
  </div>

  <div class="about">
    <p class="about-title">Sobre nós</p>
    <hr class="line">
    <p class="about-content">Levantamos as 3 características em comum do grupo, que são Inovação, Otimismo e Ousadia.
      Também tivemos uma conversa bem descontraída e divertida em que acabamos gerando o nome do grupo.</p>
  </div>

  <div class="popularity">
    <p class="title-popular">Mais Populares</p>
    <hr class="line">
    <% @blog_posts.sample(3).each do |blog| %>
    <%= link_to blog_post_path(blog.id) do %>
    <%= image_tag blog.image.variant(resize: "200x200") %>
    <p class="popularity-title">
      <%= blog.title %>
    </p>
    <%end%>
    <%end%>
  </div>
</div>
<div class="form-show">
  <%= render partial: "blog_posts/shared/leads_form" %>
</div>

app/views/greetings/index.html.erb
<div class="greeting-container">
  <div class="download">
    <p class="title-download">Seu download está pronto para ser realizado: <p>
    <div class="btn btn-warning"><%= link_to "Baixar", {controller: "greetings", action: "download", ebook: @ebook }%></div>
  </div>
  <%= image_tag "ebook-download.png", class: "ebook-image" %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <script src="https://www.gstatic.com/firebasejs/5.4.1/firebase.js"></script>
  <script async src="https://www.googletagmanager.com/gtag/js?id=UA-126695757-2"></script>
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU"
    crossorigin="anonymous">
  <link href="https://fonts.googleapis.com/css?family=Lato" rel="stylesheet">
  <title>Claquete Business</title>
  <%= favicon_link_tag 'claquete_logo.jpg' %>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= stylesheet_link_tag    'blog_posts/blog_index', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= stylesheet_link_tag    'blog_post', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= stylesheet_link_tag    'blog_posts/form', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= stylesheet_link_tag    'blog_posts/show', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= stylesheet_link_tag    'greetings/index', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag    'main_form', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <!-- Global site tag (gtag.js) - Google Analytics -->
  <script async src="https://www.googletagmanager.com/gtag/js?id=UA-126695757-2"></script>
  <script>
    window.dataLayer = window.dataLayer || [];

    function gtag() {
      dataLayer.push(arguments);
    }
    gtag('js', new Date());

    gtag('config', 'UA-126695757-2');
  </script>
</head>

<body>
  <%= render partial: "blog_posts/shared/nav" %>
  <%= yield %>
</body>

<header>
            <h1 class="logo_topo">logo</h1>        
            <ul class="icones-sociais">
                <li><a class="facebook" href="https://www.facebook.com/claquetebusiness/">Facebook</a></li>
                <li><a class="instagram" href="https://www.instagram.com/claquetebusiness/">Instagran</a></li>
            </ul>
            
            <h2 class="botao_ebook">BAIXE SEU EBOOK AGORA</h2>
    </header>

<footer>
  <p>® CLAQUETE BUSINESS 2018 | Todos os direitos reservados</p>
</footer>

</html>